services:
  fastapi:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro

    env_file:
      - ./.env
  
  postgres:

    image: postgres
    restart: always
    
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb
    env_file:
      - ./.env





